version: '2'
services:

  sut:
    build: .
    command: sh -c "npm run lint && npm t && ./tests/rest_api.sh"
    volumes:
     - ./src:/home/app/code/src
     - ./tests:/home/app/code/tests
    depends_on:
     - app
    environment:
     - "BASE_URL=http://app:8000"
     - "API_SECRET=1234"
     - "LOG_LEVEL=error"
     - "NODE_ENV="

  app:
    build: .
    volumes:
     - ./src:/home/app/code/src
    depends_on:
     - authredis
     - usermetaredis
     - directory
    environment:
     - "API_SECRET=1234"
     - "USERMETA_PUBLIC_KEYS=country,yearofbirth"
     - "USERMETA_PROTECTED_KEYS=$$friends"
     - "USERMETA_PRIVATE_KEYS=$$banned,$$alias"
     - "USERMETA_INTERNAL_KEYS="
     - "USERMETA_MAX_LENGTH=1000"
     - "REDIS_USERMETA_PORT_6379_TCP_ADDR=usermetaredis"
     - "REDIS_AUTH_PORT_6379_TCP_ADDR=authredis"
     - "NODE_ENV="
     - "LOG_LEVEL=debug"
    ports:
     - "8000:8000"

  directory:
    image: ganomede/directory:v0.3.1
    depends_on:
      - directorysync
    environment:
     - "COUCH_DIRECTORY_PORT_5984_TCP_ADDR=directorycouch"
     - "REDIS_AUTH_PORT_6379_TCP_ADDR=authredis"
     - "API_SECRET=1234"
     - "COUCH_DIRECTORY_SYNC="

  # will just sync the database
  directorysync:
    image: ganomede/directory:v0.3.1
    depends_on:
     - directorycouch
     - authredis
    environment:
     - "COUCH_DIRECTORY_PORT_5984_TCP_ADDR=directorycouch"
     - "REDIS_AUTH_PORT_6379_TCP_ADDR=authredis"
     - "API_SECRET=1234"
     - "COUCH_DIRECTORY_SYNC=1"

  directorycouch:
    image: klaemo/couchdb:1.6.1
  authredis:
    image: redis:alpine
  usermetaredis:
    image: redis:alpine
